image: ubuntu/20.04
packages:
  - pkg-config
  - libsamplerate0-dev
  - libsndfile1-dev
  - libfftw3-dev
#  - libsleef-dev
  - ladspa-sdk
  - lv2-dev
  - vamp-plugin-sdk
  - libboost-test-dev
  - meson
  - ninja-build
sources:
  - hg+https://hg.sr.ht/~breakfastquay/rubberband
tasks:
  - setup: |
      cd rubberband
      meson build
      meson build_speex -Dresampler=speex
      meson build_libsamplerate -Dresampler=libsamplerate
      meson build_fftw -Dfft=fftw
#      meson build_sleef -Dfft=sleef
      meson build_kissfft -Dfft=kissfft
  - build: |
      cd rubberband
      ninja -C build
      meson test -C build
      build/rubberband -V
      ninja -C build_speex
      meson test -C build_speex
      build_speex/rubberband -V
      ninja -C build_libsamplerate
      meson test -C build_libsamplerate
      build_libsamplerate/rubberband -V
      ninja -C build_fftw
      meson test -C build_fftw
#      ninja -C build_sleef
#      meson test -C build_sleef
      build_fftw/rubberband -V
      ninja -C build_kissfft
      meson test -C build_kissfft
      build_kissfft/rubberband -V
      ./otherbuilds/check.sh
triggers:
  - action: email
    condition: always
    to: chris.cannam@breakfastquay.com
    
